# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Schemalint < Formula
  desc "JSON Schema linter and generator for static type compatibility"
  homepage "https://github.com/grokify/schemalint"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grokify/schemalint/releases/download/v0.3.0/schemalint_0.3.0_darwin_amd64.tar.gz"
      sha256 "a34209b87162b0934b76a9ace8e147777a8a8686cf15826eced479ffdcd3ca1c"

      def install
        bin.install "schemalint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grokify/schemalint/releases/download/v0.3.0/schemalint_0.3.0_darwin_arm64.tar.gz"
      sha256 "8d0c560fee56dda4579a453f0b90484c3836db140beb7cd868b9b57d726cb749"

      def install
        bin.install "schemalint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/schemalint/releases/download/v0.3.0/schemalint_0.3.0_linux_amd64.tar.gz"
      sha256 "2fd8cf4e2f8a1d8181b244670d50d7808ffb1b6c024cbb131465712288ecaecf"
      def install
        bin.install "schemalint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/schemalint/releases/download/v0.3.0/schemalint_0.3.0_linux_arm64.tar.gz"
      sha256 "597f9b1bb14c515144c2925c725bee470835dff0ab1d5b996a7c24994cf88cbb"
      def install
        bin.install "schemalint"
      end
    end
  end

  test do
    system "#{bin}/schemalint", "version"
  end
end
