# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Splan < Formula
  desc "CLI for structured planning documents (PRD, MRD, TRD, OKR, V2MOM)"
  homepage "https://github.com/grokify/structured-plan"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grokify/structured-plan/releases/download/v0.5.0/splan_0.5.0_darwin_amd64.tar.gz"
      sha256 "0aaa8abe6b897a190bc7edd1180ced4d760e4e6ed309c790778be3ba78a34b1c"

      def install
        bin.install "splan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grokify/structured-plan/releases/download/v0.5.0/splan_0.5.0_darwin_arm64.tar.gz"
      sha256 "23d1030a071d1ef9dcf782a5951951c4aaa9b8fb0becb6e1b14056fe76504f7e"

      def install
        bin.install "splan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-plan/releases/download/v0.5.0/splan_0.5.0_linux_amd64.tar.gz"
      sha256 "39da33b130353bdb18d193723eb43e639defe6bc309e8e77dee96f54c21595c8"
      def install
        bin.install "splan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-plan/releases/download/v0.5.0/splan_0.5.0_linux_arm64.tar.gz"
      sha256 "f1c71977455123c7d3ce252d2e966b02c42093e994359b38abe710beb26278af"
      def install
        bin.install "splan"
      end
    end
  end

  test do
    system "#{bin}/splan", "--version"
  end
end
