# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StructuredRoadmap < Formula
  desc "CLI for machine-readable project roadmaps using JSON IR"
  homepage "https://github.com/grokify/structured-roadmap"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grokify/structured-roadmap/releases/download/v0.2.1/structured-roadmap_0.2.1_darwin_amd64.tar.gz"
      sha256 "66fec35334cc95e7bf3dbed0aa29e117040863b40d5693c1777696bc743ab040"

      def install
        bin.install "sroadmap"
        bin.install_symlink "sroadmap" => "structured-roadmap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grokify/structured-roadmap/releases/download/v0.2.1/structured-roadmap_0.2.1_darwin_arm64.tar.gz"
      sha256 "ec57572f5e21dbfac3df8b89d0cf6baa72b13ce55241113186c28d0e701db679"

      def install
        bin.install "sroadmap"
        bin.install_symlink "sroadmap" => "structured-roadmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-roadmap/releases/download/v0.2.1/structured-roadmap_0.2.1_linux_amd64.tar.gz"
      sha256 "44604a58e361d011afff29b9f3c941b9dd5a46346c7d47438e55470db70200b9"
      def install
        bin.install "sroadmap"
        bin.install_symlink "sroadmap" => "structured-roadmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-roadmap/releases/download/v0.2.1/structured-roadmap_0.2.1_linux_arm64.tar.gz"
      sha256 "a610401b09523a551f84b5dcbfec4428dfa10a5b66696be51a3a3ca967363066"
      def install
        bin.install "sroadmap"
        bin.install_symlink "sroadmap" => "structured-roadmap"
      end
    end
  end

  test do
    system "#{bin}/sroadmap", "version"
  end
end
