# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StructuredTasks < Formula
  desc "CLI for machine-readable project task lists using JSON IR"
  homepage "https://github.com/grokify/structured-tasks"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grokify/structured-tasks/releases/download/v0.3.0/structured-tasks_0.3.0_darwin_amd64.tar.gz"
      sha256 "9b4f687f6dabda11a5935b29bcb684ba189e952988389c7a152645dbbecc254a"

      def install
        bin.install "stasks"
        bin.install_symlink "stasks" => "structured-tasks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grokify/structured-tasks/releases/download/v0.3.0/structured-tasks_0.3.0_darwin_arm64.tar.gz"
      sha256 "2e4f162d0b0eb796f66a3548ff0b25b202665560720a2611af5b62173866bdf5"

      def install
        bin.install "stasks"
        bin.install_symlink "stasks" => "structured-tasks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-tasks/releases/download/v0.3.0/structured-tasks_0.3.0_linux_amd64.tar.gz"
      sha256 "1462b211c889faf33296bc3e799fa908f3792773bab0de2fd00626bb8d8a8ac4"
      def install
        bin.install "stasks"
        bin.install_symlink "stasks" => "structured-tasks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-tasks/releases/download/v0.3.0/structured-tasks_0.3.0_linux_arm64.tar.gz"
      sha256 "dfd5888c95c3dfc3d05963b00041dc9da37d926e4525988b6ef6d0cda8058b98"
      def install
        bin.install "stasks"
        bin.install_symlink "stasks" => "structured-tasks"
      end
    end
  end

  test do
    system "#{bin}/stasks", "version"
  end
end
