# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StructuredChangelog < Formula
  desc "CLI for canonical, deterministic changelogs using JSON IR"
  homepage "https://github.com/grokify/structured-changelog"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.5.0/structured-changelog_0.5.0_darwin_amd64.tar.gz"
      sha256 "0e3c81df98e8f0cae30bf3ff93943294270cb03327e35ad319833992a29fa911"

      def install
        bin.install "sclog"
        bin.install_symlink "sclog" => "structured-changelog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.5.0/structured-changelog_0.5.0_darwin_arm64.tar.gz"
      sha256 "1e16e75e6e4509fbb2f70c684d899523cc3152552e3737f210d50854d6921b58"

      def install
        bin.install "sclog"
        bin.install_symlink "sclog" => "structured-changelog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.5.0/structured-changelog_0.5.0_linux_amd64.tar.gz"
      sha256 "ea5f0aac6b212a29e5b72fafc709182e8ca9b82dce37913208f5eed505ce6412"
      def install
        bin.install "sclog"
        bin.install_symlink "sclog" => "structured-changelog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.5.0/structured-changelog_0.5.0_linux_arm64.tar.gz"
      sha256 "ee6a3d8cd73e87a76ea7242855e22370eb5359c16a2e8d8e0771a76a62ca3de7"
      def install
        bin.install "sclog"
        bin.install_symlink "sclog" => "structured-changelog"
      end
    end
  end

  test do
    system "#{bin}/sclog", "version"
  end
end
