# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StructuredChangelog < Formula
  desc "CLI for canonical, deterministic changelogs using JSON IR"
  homepage "https://github.com/grokify/structured-changelog"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.9.0/structured-changelog_0.9.0_darwin_amd64.tar.gz"
      sha256 "b315cab1886ff44c22294591302ea6f905836138854b1cc69130b67d04b32c20"

      def install
        bin.install "schangelog"
        bin.install_symlink "schangelog" => "structured-changelog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.9.0/structured-changelog_0.9.0_darwin_arm64.tar.gz"
      sha256 "343aee2a27e613a42cf9906a5c65c2f27ea685caa854ae52c2b7720b294d89af"

      def install
        bin.install "schangelog"
        bin.install_symlink "schangelog" => "structured-changelog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.9.0/structured-changelog_0.9.0_linux_amd64.tar.gz"
      sha256 "b80192f305c057c88149130e3c5389df8b6c03f05d3e9a253f7c88bfc72f0580"
      def install
        bin.install "schangelog"
        bin.install_symlink "schangelog" => "structured-changelog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.9.0/structured-changelog_0.9.0_linux_arm64.tar.gz"
      sha256 "d50a956d63e381b0f98849e7a1faac688326f2b605b35d87e18679a3f86cdb4d"
      def install
        bin.install "schangelog"
        bin.install_symlink "schangelog" => "structured-changelog"
      end
    end
  end

  test do
    system "#{bin}/schangelog", "version"
  end
end
