# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StructuredRoadmap < Formula
  desc "CLI for machine-readable project roadmaps using JSON IR"
  homepage "https://github.com/grokify/structured-roadmap"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grokify/structured-roadmap/releases/download/v0.2.0/structured-roadmap_0.2.0_darwin_amd64.tar.gz"
      sha256 "98b1a43451815d1dfa7105bc55aec1bc75227cf1dd2070fd78b497bc83d45780"

      def install
        bin.install "sroadmap"
        bin.install_symlink "sroadmap" => "structured-roadmap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grokify/structured-roadmap/releases/download/v0.2.0/structured-roadmap_0.2.0_darwin_arm64.tar.gz"
      sha256 "4729d708e0d93e27dafecdc77c25beb0427547aa90422c2ef4202ce506ae718d"

      def install
        bin.install "sroadmap"
        bin.install_symlink "sroadmap" => "structured-roadmap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-roadmap/releases/download/v0.2.0/structured-roadmap_0.2.0_linux_amd64.tar.gz"
      sha256 "34648b99a84e8f8273ba1d220fc92ac8ad9ec6e4099ea9b14e0c27c4dcbfcade"
      def install
        bin.install "sroadmap"
        bin.install_symlink "sroadmap" => "structured-roadmap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-roadmap/releases/download/v0.2.0/structured-roadmap_0.2.0_linux_arm64.tar.gz"
      sha256 "c89293e7ed48b4bbc02c436185990a39cda5b60bad0c1dabb54f6884e0355944"
      def install
        bin.install "sroadmap"
        bin.install_symlink "sroadmap" => "structured-roadmap"
      end
    end
  end

  test do
    system "#{bin}/sroadmap", "version"
  end
end
