# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StructuredChangelog < Formula
  desc "CLI for canonical, deterministic changelogs using JSON IR"
  homepage "https://github.com/grokify/structured-changelog"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.6.0/structured-changelog_0.6.0_darwin_amd64.tar.gz"
      sha256 "dacdfccfb7ba82ca022fd275c30825cd7806ddd165f7c330cbb85d650b210758"

      def install
        bin.install "sclog"
        bin.install_symlink "sclog" => "structured-changelog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.6.0/structured-changelog_0.6.0_darwin_arm64.tar.gz"
      sha256 "20251bd16975dd79184a8b5b85f8d0f28d5cf8c005450c61a3776df7a1e6ce15"

      def install
        bin.install "sclog"
        bin.install_symlink "sclog" => "structured-changelog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.6.0/structured-changelog_0.6.0_linux_amd64.tar.gz"
      sha256 "055821724b9f7e9829e29f6f96968c0434d1582a44900e88db9ec6df5e60974b"
      def install
        bin.install "sclog"
        bin.install_symlink "sclog" => "structured-changelog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grokify/structured-changelog/releases/download/v0.6.0/structured-changelog_0.6.0_linux_arm64.tar.gz"
      sha256 "456413a321806ddff49ace2037950404661359f775940fe3df8035e4238a7d0e"
      def install
        bin.install "sclog"
        bin.install_symlink "sclog" => "structured-changelog"
      end
    end
  end

  test do
    system "#{bin}/sclog", "version"
  end
end
